apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-dukp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-dukp@sha256:8220f8fbf2dca3193d9e2060523143fa3db98fbf65419faf2fb2e8fd62031fd7
        name: my-python
        resources: {}
status: {}
